#!/usr/bin/env sh

./build/test1 --urls \
https://google.com,\
https://facebook.com,\
https://amazon.com,\
https://imdb.com,\
https://apple.com,\
https://merriam-webster.com,\
https://pinterest.com,\
https://yelp.com,\
https://tripadvisor.com,\
https://wiktionary.org,\
https://dictionary.com,\
https://yahoo.com,\
https://cambridge.org,\
https://britannica.com,\
https://weather.com,\
https://microsoft.com,\
https://walmart.com,\
https://espn.com,\
https://linkedin.com,\
https://homedepot.com,\
https://espncricinfo.com,\
https://craigslist.org,\
https://dogs.com,\
https://gsmarena.com,\
https://mayoclinic.org,\
https://cricbuzz.com,\
https://timeanddate.com,\
https://webmd.com,\
https://thesaurus.com,\
https://whatsapp.com,\
https://rottentomatoes.com,\
https://bbc.com,\
https://bestbuy.com,\
https://healthline.com,\
https://netflix.com,\
https://indeed.com,\
https://thefreedictionary.com,\
https://cats.com,\
https://spotify.com,\
https://livescore.com,\
https://ebay.com,\
https://reddit.com,\
https://ytmp3.cc,\
https://samsung.com,\
https://nih.gov,\
https://tiktok.com,\
https://steampowered.com,\
https://investopedia.com,\
https://cdc.gov,\
https://nordstrom.com,\
https://blog.google,\
https://cnbc.com,\
https://indiatimes.com,\
https://roblox.com,\
https://flashscore.com,\
https://thepiratebay.org,\
https://adobe.com,\
https://cnn.com,\
https://speedtest.net,\
https://ssyoutube.com,\
https://unsplash.com,\
https://lowes.com,\
https://vocabulary.com,\
https://marketwatch.com,\
https://mcdonalds.com,\
https://deepl.com,\
https://playstation.com,\
https://bloomberg.com,\
https://forbes.com,\
https://livescore.in,\
https://booking.com,\
https://clevelandclinic.org,\
https://xe.com,\
https://friv.com,\
https://coinmarketcap.com,\
https://spanishdict.com,\
https://goodhousekeeping.com,\
https://instructure.com,\
https://dominos.com,\
https://wunderground.com,\
https://yourdictionary.com,\
https://cnet.com,\
https://twitch.tv,\
https://pexels.com,\
https://poki.com,\
https://caranddriver.com,\
https://github.com,\
https://hotels.com,\
https://globo.com,\
https://soundcloud.com,\
https://theguardian.com,\
https://usnews.com,\
https://livescores.com,\
https://wellsfargo.com,\
https://parade.com,\
https://expedia.com,\
https://foxnews.com,\
https://realtor.com,\
https://crazygames.com
